### ISSUE TITLE
How to make it as developer mode

### ISSUE THREAD

**Issue by binfask** [pararell/eshop-angular-node#1]
How to make this to development mode? because each and every time we need to build the application to dist folder, so it is taking more time

**Comment by pararell** [comment]
You can serve application by default on localhost:5000. If you want work on development mode with frontend part, set in api.service.ts  baseUrl = 'localhost:5000'; Then for FE use angular/cli and 'ng serve' command, it will be on localhost:4200. For BE it isn't set up, just use 'npm run ssr:webpack' for BE changes ,then 'npm run start'.
